# Generated by Django 5.0.6 on 2024-10-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0016_goodskeyword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
